---
    packages:
      - git
      - nginx
      - python-pip
      - python-setuptools
      - mongodb-org
      - nodejs
      - redis-server

    pippackages:
      - pymongo

    MONGO_USER: "{{ lookup('env','MONGO_USER') }}"
    MONGO_PASSWORD: "{{ lookup('env','MONGO_PASSWORD') }}"
    MAIL_USER: "{{ lookup('env','MAIL_USER') }}"
    MAIL_PASSWORD: "{{ lookup('env','MAIL_PASSWORD') }}"
    MAIL_SMTP: "{{ lookup('env','MAIL_SMTP') }}"
...
