---
- hosts: Stable

  gather_facts: no

  tasks:
      # Add environment variables
    - name: Add environment variables
      template:
        src: /etc/environment
        dest: /etc/environment
      become: yes

      # Restart the server to set environment variables
    - name: Restarting Server
      become: yes
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
      async: 1
      poll: 0

      # Wait for server to reboot
    - name: Wait for reboot
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=10 state=started
      become: false
...
