---
      # Add environment variables
    - name: Add environment variables
      template:
        src: variables
        dest: /etc/environment
      become: yes

      # Restart the server to set environment variables
    - name: Restarting Server
      become: yes
      shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
      async: 1
      poll: 0

      # Wait for server to reboot
    - name: Wait for reboot
      local_action: wait_for host={{ inventory_hostname }} port=22 delay=10 state=started
      become: false

    # Install python to use ansible
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

    - name: import mongodb public KEY
      apt_key:
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
        keyserver: keyserver.ubuntu.com

    - name: Create a list file for mongodb
      apt_repository:
        repo: 'deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse'
        state: present

    - name: Install apt packages
      become: yes
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items: "{{ packages }}"

    - name: Create /data/db
      file:
        path: /data/db
        state: directory
        mode: 0777

      # Change bindIP to accept all connections
    - name: Create the mongodb configuration file with auth
      template: src=mongo.config dest=/etc/mongod.conf owner=mongodb group=mongodb mode=0400

    - name: Start mongodb service
      command: service mongod start
      become: yes

    - name: install python setuptools
      apt: pkg=python-setuptools state=present
      become: yes

    - name: install pymongo
      shell: python -m easy_install pymongo
      become: yes

    - name: create mongodb admin user
      mongodb_user:
        database: admin
        name: "{{MONGO_USER}}"
        password: "{{MONGO_PASSWORD}}"
        roles:
          - { db: "admin", role: "readWrite" }
          - { db: "admin", role: "dbAdmin" }
          - { db: "admin", role: "userAdmin" }
        login_port: 27017
        state: present
